"use client";

import { useState, useEffect } from "react";
import { useParams, useRouter } from "next/navigation";
import DashboardLayout from "@/components/layout/DashboardLayout";
import Badge from "@/components/ui/Badge";
import Link from "next/link";
import {
  Phone,
  Mail,
  Lock,
  MessageSquare,
  Building2,
  Calendar,
  User,
  Plus,
  Send,
  ExternalLink,
  ChevronLeft,
  CheckCircle2,
  Copy,
  Check,
  Sparkles,
  AlertCircle,
  Clock,
  Briefcase,
  CreditCard,
} from "lucide-react";
import { PageLoadingSpinner } from "@/components/ui/Skeleton";

export default function AdminClientLogPage() {
  const params = useParams();
  const router = useRouter();
  const id = (Array.isArray(params?.id) ? params.id[0] : params?.id) || "d101";

  const [deal, setDeal] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [copiedText, setCopiedText] = useState("");

  // Interaction log state
  const [interactions, setInteractions] = useState<any[]>([
    {
      date: "Day 3, 11:45 AM",
      type: "call",
      handledBy: "CEO Pasha (GWD Global)",
      summary: "Spoke with Dr. Sharma. Confirmed interest generated by Arjun Reddy. Pitched formal online booking module.",
      outcome: "Hot Lead — Proposal Requested",
    },
    {
      date: "Day 3, 02:30 PM",
      type: "email",
      handledBy: "Admin Sales Lead",
      summary: "Sent formal proposal and ₹35,000 Razorpay payment link on official GWD letterhead.",
      outcome: "Proposal Sent",
    },
  ]);

  const [newType, setNewType] = useState("call");
  const [newSummary, setNewSummary] = useState("");
  const [newOutcome, setNewOutcome] = useState("Call Successful / Follow-up Needed");
  const [submittingLog, setSubmittingLog] = useState(false);

  useEffect(() => {
    async function fetchDeal() {
      try {
        const res = await fetch(`/api/deals/${id}`);
        if (res.ok) {
          const data = await res.json();
          setDeal(data.deal);
        } else {
          // Fallback demo data
          setDeal({
            _id: id,
            clientName: "Dr. Sharma",
            clientBusiness: "Sunshine Dental Clinic",
            clientPhone: "+91 99800 55443",
            clientEmail: "doctor@sunshinedental.com",
            serviceType: "Appointment Booking Engine + SEO",
            dealValue: 35000,
            gwdFinalDealValue: 35000,
            status: "proposal_sent",
            dealArchitectId: { name: "Arjun Reddy", participantRole: "Deal Architect" },
            teamId: { name: "Team Phoenix (#1)", emoji: "🔥" },
          });
        }
      } catch (err) {
        console.error("Error fetching deal:", err);
      } finally {
        setLoading(false);
      }
    }
    fetchDeal();
  }, [id]);

  const handleAddLog = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newSummary.trim()) return;
    setSubmittingLog(true);

    try {
      let action = "gwd_contacted";
      if (newOutcome.includes("Proposal Sent")) action = "proposal_sent";
      else if (newOutcome.includes("Payment Confirmed")) action = "gwd_close_paid";

      const res = await fetch(`/api/deals/${id}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          action,
          adminId: "CEO Pasha / GWD Sales",
          internalNotes: `[${newType.toUpperCase()}] ${newSummary} (${newOutcome})`,
        }),
      });

      if (res.ok) {
        const updated = await res.json();
        if (updated.deal) {
          setDeal((prev: any) => ({ ...prev, ...updated.deal }));
        }
      }
    } catch (err) {
      console.error("Error logging interaction:", err);
    } finally {
      setInteractions((prev) => [
        {
          date: new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }),
          type: newType,
          handledBy: "CEO Pasha / GWD Sales",
          summary: newSummary,
          outcome: newOutcome,
        },
        ...prev,
      ]);
      setNewSummary("");
      setSubmittingLog(false);
    }
  };

  const copyToClipboard = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    setCopiedText(label);
    setTimeout(() => setCopiedText(""), 2000);
  };

  if (loading) {
    return (
      <DashboardLayout title="Client Vault" breadcrumbs={["Home", "Admin", "Deals", "Client Vault"]}>
        <PageLoadingSpinner message="Opening GWD Secure Client Contact Vault..." />
      </DashboardLayout>
    );
  }

  const phoneRaw = (deal?.clientPhone || "+919980055443").replace(/[^0-9+]/g, "");

  // Professional WhatsApp Templates
  const templates = [
    {
      label: "Template A — First Contact Following Participant Pitch",
      text: `Hi ${deal?.clientName || "Dr. Sharma"}, this is the GWD Global Sales Team following up on your discussion with ${deal?.dealArchitectId?.name || "our representative"} regarding ${deal?.serviceType || "digital services"} for ${deal?.clientBusiness || "your business"}.\n\nGWD Global is a registered digital services company based in Hyderabad. All formal contracts and billing are handled directly by us to ensure 100% quality delivery.\n\nWould you be available for a quick 10-minute call today to go over the official proposal?`,
    },
    {
      label: "Template B — Razorpay Invoice & Payment Link Note",
      text: `Hi ${deal?.clientName || "Dr. Sharma"}, please find your official GWD Global payment link for ${deal?.clientBusiness || "your project"} (${deal?.serviceType || "service"}).\n\nEstimated Value: ₹${Number(deal?.gwdFinalDealValue || deal?.dealValue || 35000).toLocaleString()}\nSecure Payment Link: https://razorpay.me/@gwdglobal\n\nOnce payment is completed, our project management team will initiate onboarding within 24 hours!`,
    },
    {
      label: "Template C — Pre-Delivery QA & Final Hand-off",
      text: `Hi ${deal?.clientName || "Dr. Sharma"}, fantastic news! Our engineering team has completed quality assurance on your ${deal?.serviceType || "project"}.\n\nYou can review the live preview here: https://sunshine-dental-preview.vercel.app\n\nPlease reply with any feedback or your confirmation for official sign-off!`,
    },
  ];

  return (
    <DashboardLayout title={`Secure Client Log — ${deal?.clientBusiness}`} breadcrumbs={["Home", "Admin", "Deals", `#${id}`, "Vault Log"]}>
      <div className="animate-slide-up space-y-6">
        {/* Top Bar */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-2">
          <Link
            href="/admin/deals"
            className="flex items-center gap-2 min-h-[44px] text-sm font-bold text-[var(--text-secondary)] hover:text-[var(--crimson)] transition-colors active:scale-98"
          >
            <ChevronLeft className="w-4 h-4" /> Back to 5-Stage Deals Command
          </Link>
          <Badge variant="success" size="md" className="flex items-center gap-1.5 font-mono text-xs shadow-2xs self-start sm:self-auto">
            <Lock className="w-3.5 h-3.5" /> GWD ADMIN VAULT ACCESS ONLY
          </Badge>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Left 2 Cols: Client Vault Profile & Interaction Log */}
          <div className="lg:col-span-2 space-y-6">
            {/* Client Profile Vault Card */}
            <div className="card-glass p-6 border-2 border-emerald-500/30 bg-gradient-to-br from-emerald-500/5 via-transparent to-transparent shadow-md transition-all hover:shadow-lg">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b border-[var(--border)]">
                <div>
                  <span className="text-xs font-extrabold text-emerald-600 dark:text-emerald-400 uppercase tracking-wider flex items-center gap-1.5 font-mono">
                    <Lock className="w-4 h-4 text-emerald-500" /> Protected Client Vault Record
                  </span>
                  <h1 className="text-2xl sm:text-3xl font-extrabold text-[var(--text-primary)] mt-1.5 font-display tracking-tight">
                    {deal?.clientBusiness || "Sunshine Dental Clinic"}
                  </h1>
                  <p className="text-sm text-[var(--text-secondary)] mt-1 font-medium">
                    Decision Maker: <strong className="text-[var(--text-primary)]">{deal?.clientName || "Dr. Sharma"}</strong> &nbsp;•&nbsp; Deal #{id}
                  </p>
                </div>
                <div className="text-left sm:text-right bg-[var(--surface-alt)] p-3.5 rounded-xl border border-[var(--border)]">
                  <div className="text-[10px] font-bold text-[var(--text-muted)] uppercase tracking-wider">Originating Squad</div>
                  <div className="text-sm font-bold text-[var(--crimson)] font-mono mt-0.5">{deal?.teamId?.emoji || "🔥"} {deal?.teamId?.name || "Phoenix Squad"}</div>
                  <div className="text-xs text-[var(--text-secondary)] font-medium mt-0.5">DA: <strong className="text-[var(--text-primary)]">{deal?.dealArchitectId?.name || "Arjun Reddy"}</strong></div>
                </div>
              </div>

            <div className="pt-6 grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="p-4 rounded-xl bg-[var(--surface-alt)] border border-[var(--border)] flex items-center justify-between">
                <div>
                  <div className="text-xs font-bold text-[var(--text-muted)] uppercase tracking-wider flex items-center gap-1.5">
                    <Phone className="w-3.5 h-3.5 text-emerald-500" /> Phone / WhatsApp
                  </div>
                  <div className="text-base font-black text-emerald-600 dark:text-emerald-400 font-mono mt-1">
                    {deal?.clientPhone || "+91 99800 55443"}
                  </div>
                </div>
                <div className="flex gap-1.5">
                  <a
                    href={`tel:${phoneRaw}`}
                    className="p-2 rounded-lg bg-emerald-600 text-white hover:bg-emerald-700 transition-colors"
                    title="Call directly"
                  >
                    <Phone className="w-4 h-4" />
                  </a>
                  <button
                    onClick={() => copyToClipboard(deal?.clientPhone || "+919980055443", "phone")}
                    className="p-2 rounded-lg bg-[var(--surface)] border hover:bg-gray-100 transition-colors"
                    title="Copy Phone"
                  >
                    {copiedText === "phone" ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4 text-[var(--text-secondary)]" />}
                  </button>
                </div>
              </div>

              <div className="p-4 rounded-xl bg-[var(--surface-alt)] border border-[var(--border)] flex items-center justify-between">
                <div>
                  <div className="text-xs font-bold text-[var(--text-muted)] uppercase tracking-wider flex items-center gap-1.5">
                    <Mail className="w-3.5 h-3.5 text-blue-500" /> Email Address
                  </div>
                  <div className="text-sm font-bold text-[var(--text-primary)] mt-1 truncate">
                    {deal?.clientEmail || "doctor@sunshinedental.com"}
                  </div>
                </div>
                <div className="flex gap-1.5">
                  <a
                    href={`mailto:${deal?.clientEmail || "doctor@sunshinedental.com"}`}
                    className="p-2 rounded-lg bg-blue-600 text-white hover:bg-blue-700 transition-colors"
                    title="Send Email"
                  >
                    <Mail className="w-4 h-4" />
                  </a>
                  <button
                    onClick={() => copyToClipboard(deal?.clientEmail || "doctor@sunshinedental.com", "email")}
                    className="p-2 rounded-lg bg-[var(--surface)] border hover:bg-gray-100 transition-colors"
                    title="Copy Email"
                  >
                    {copiedText === "email" ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4 text-[var(--text-secondary)]" />}
                  </button>
                </div>
              </div>
            </div>
          </div>

          {/* Log New Interaction Form */}
          <div className="card p-6 border border-[var(--border)] shadow-sm">
            <h3 className="text-lg font-bold mb-2">
              Log GWD Client Interaction
            </h3>
            <p className="text-xs text-[var(--text-secondary)] mb-4">
              Record every phone call, email, or WhatsApp follow-up to maintain complete audit tracking of GWD Sales efforts.
            </p>
            <form onSubmit={handleAddLog} className="space-y-4">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-bold mb-1">Interaction Type *</label>
                  <select
                    value={newType}
                    onChange={(e) => setNewType(e.target.value)}
                    className="w-full px-3 py-2 border border-[var(--border)] rounded-xl text-xs bg-white dark:bg-black/40"
                  >
                    <option value="call">📞 Phone Call</option>
                    <option value="whatsapp">💬 WhatsApp Chat / Follow-up</option>
                    <option value="email">📧 Email / Proposal Sent</option>
                    <option value="meeting">🤝 In-Person / Zoom Meeting</option>
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-bold mb-1">Status / Outcome *</label>
                  <select
                    value={newOutcome}
                    onChange={(e) => setNewOutcome(e.target.value)}
                    className="w-full px-3 py-2 border border-[var(--border)] rounded-xl text-xs bg-white dark:bg-black/40 font-semibold"
                  >
                    <option value="Call Successful / Follow-up Needed">Active Follow-up Needed</option>
                    <option value="Hot Lead — Proposal Sent">Hot Lead — Proposal Sent</option>
                    <option value="Ready to Pay / Invoice Requested">Ready to Pay / Invoice Requested</option>
                    <option value="Payment Confirmed via Razorpay">Payment Confirmed via Razorpay</option>
                    <option value="Client Unresponsive / Busy">Client Unresponsive / Busy</option>
                    <option value="Cold Lead / Unqualified">Cold Lead / Unqualified</option>
                  </select>
                </div>
              </div>
              <div>
                <label className="block text-xs font-bold mb-1">Interaction Summary & Notes *</label>
                <textarea
                  required
                  rows={2}
                  value={newSummary}
                  onChange={(e) => setNewSummary(e.target.value)}
                  placeholder="e.g., Spoke with Dr. Sharma. He liked our pricing of ₹35K and requested official Razorpay invoice link via WhatsApp."
                  className="w-full px-3 py-2 border border-[var(--border)] rounded-xl text-xs resize-none"
                />
              </div>
              <div className="flex justify-end pt-1">
                <button
                  type="submit"
                  disabled={submittingLog || !newSummary.trim()}
                  className="px-5 py-2 bg-[var(--crimson)] text-white rounded-xl text-xs font-bold hover:bg-[var(--crimson-dark)] transition-colors shadow-sm flex items-center gap-1.5 disabled:opacity-50"
                >
                  <Plus className="w-4 h-4" /> Log Interaction Entry
                </button>
              </div>
            </form>
          </div>

          {/* Interaction History List */}
          <div className="card p-6 border border-[var(--border)] shadow-sm">
            <h3 className="text-lg font-bold mb-4">
              Interaction History & Audit Trail ({interactions.length})
            </h3>
            <div className="space-y-4">
              {interactions.map((log, i) => (
                <div key={i} className="p-4 rounded-xl bg-[var(--surface-alt)] border border-[var(--border)] flex items-start justify-between gap-4">
                  <div className="flex items-start gap-3">
                    <div className="w-8 h-8 rounded-full bg-[var(--crimson-pale)] text-[var(--crimson)] flex items-center justify-center text-sm shrink-0">
                      {log.type === "call" ? "📞" : log.type === "whatsapp" ? "💬" : log.type === "email" ? "📧" : "🤝"}
                    </div>
                    <div>
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="text-xs font-bold uppercase tracking-wider text-[var(--text-primary)]">
                          {log.type.toUpperCase()} INTERACTION
                        </span>
                        <span className="text-[11px] text-[var(--text-muted)]">• {log.date}</span>
                        <Badge variant="default" size="sm">{log.outcome}</Badge>
                      </div>
                      <p className="text-xs text-[var(--text-secondary)] mt-1.5 leading-relaxed">
                        {log.summary}
                      </p>
                      <div className="text-[10px] text-[var(--text-muted)] mt-1 font-medium">
                        Handled by: {log.handledBy}
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Right 1 Col: WhatsApp Templates & Razorpay Helper */}
        <div className="space-y-6">
          {/* Razorpay Invoice Quick Helper */}
          <div className="card p-5 border border-[var(--border)] shadow-sm bg-[var(--crimson-pale)]/30">
            <h3 className="font-bold text-sm text-[var(--crimson)] uppercase tracking-wider mb-2 flex items-center gap-1.5">
              <CreditCard className="w-4 h-4" /> Official GWD Payment Helper
            </h3>
            <p className="text-xs text-[var(--text-secondary)] leading-relaxed mb-3">
              Always send the official GWD Razorpay link. Never allow direct participant UPI transfers.
            </p>
            <div className="p-3 rounded-lg bg-white dark:bg-[var(--surface)] border border-[var(--border)] font-mono text-xs text-[var(--text-primary)] mb-3 break-all">
              https://razorpay.me/@gwdglobal?amount={Number(deal?.gwdFinalDealValue || deal?.dealValue || 35000) * 100}
            </div>
            <button
              onClick={() => copyToClipboard(`https://razorpay.me/@gwdglobal?amount=${Number(deal?.gwdFinalDealValue || deal?.dealValue || 35000) * 100}`, "razor")}
              className="w-full py-2 bg-[var(--crimson)] hover:bg-[var(--crimson-dark)] text-white rounded-xl text-xs font-bold flex items-center justify-center gap-1.5 shadow-sm transition-colors"
            >
              {copiedText === "razor" ? <Check className="w-4 h-4" /> : <Copy className="w-3.5 h-3.5" />}
              <span>Copy Razorpay Payment URL</span>
            </button>
          </div>

          {/* Professional GWD WhatsApp Templates */}
          <div className="card p-5 border border-[var(--border)] shadow-sm">
            <h3 className="font-bold text-sm mb-3 flex items-center gap-1.5">
              <MessageSquare className="w-4 h-4 text-green-500" /> One-Click WhatsApp Templates
            </h3>
            <p className="text-xs text-[var(--text-secondary)] mb-4">
              Pre-approved templates for GWD Admins communicating on official business letterhead.
            </p>
            <div className="space-y-4">
              {templates.map((t, idx) => (
                <div key={idx} className="p-3.5 rounded-xl bg-[var(--surface-alt)] border border-[var(--border)] space-y-2.5">
                  <div className="text-xs font-bold text-[var(--text-primary)] flex items-center justify-between">
                    <span>{t.label}</span>
                  </div>
                  <p className="text-[11px] text-[var(--text-secondary)] whitespace-pre-wrap bg-white/70 dark:bg-black/30 p-2.5 rounded-lg border font-sans">
                    {t.text}
                  </p>
                  <div className="flex gap-2">
                    <button
                      onClick={() => copyToClipboard(t.text, `t_${idx}`)}
                      className="flex-1 py-1.5 bg-white dark:bg-black/40 border rounded-lg text-[11px] font-bold hover:bg-gray-100 flex items-center justify-center gap-1"
                    >
                      {copiedText === `t_${idx}` ? <Check className="w-3.5 h-3.5 text-green-500" /> : <Copy className="w-3.5 h-3.5" />}
                      Copy Text
                    </button>
                    <a
                      href={`https://wa.me/${phoneRaw}?text=${encodeURIComponent(t.text)}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex-1 py-1.5 bg-green-600 hover:bg-green-700 text-white rounded-lg text-[11px] font-bold flex items-center justify-center gap-1 transition-colors"
                    >
                      <Send className="w-3.5 h-3.5" /> Open WhatsApp
                    </a>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
      </div>
    </DashboardLayout>
  );
}
